"""profiles with rls

Revision ID: 040e8abf27ea
Revises: d1272af85293
Create Date: 2025-09-18 18:58:15.622440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040e8abf27ea'
down_revision: Union[str, None] = 'd1272af85293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('first_name', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('last_name', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('birthdate', sa.Date(), nullable=True))
    op.drop_column('profiles', 'display_name')
    
    op.execute("""
    ALTER TABLE public.profiles
    ADD CONSTRAINT fk_profiles_auth_users
    FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
    """)
    # ### end Alembic commands ###
    
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('display_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'birthdate')
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'first_name')
    # ### end Alembic commands ###
