"""unique constrain one card per merchant per user 

Revision ID: 296e35475230
Revises: 6eb2ef780c49
Create Date: 2025-09-18 15:56:09.833535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296e35475230'
down_revision: Union[str, None] = '6eb2ef780c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_wallet_cards_user_program', 'wallet_cards', ['user_id', 'program_id'])
    op.create_unique_constraint('uq_card_device', 'wallet_device_regs', ['card_id', 'device_library_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_card_device', 'wallet_device_regs', type_='unique')
    op.drop_constraint('uq_wallet_cards_user_program', 'wallet_cards', type_='unique')
    # ### end Alembic commands ###
