"""add_wallet_foreground_color

Revision ID: 381781fb05f6
Revises: 57c063ec0fe3
Create Date: 2025-10-24 18:37:27.483388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381781fb05f6'
down_revision: Union[str, None] = '57c063ec0fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('wallet_foreground_color', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'wallet_foreground_color')
    # ### end Alembic commands ###
