"""add_expiration_and_enhanced_tracking

Revision ID: 414e1a985da3
Revises: d89252a2c25d
Create Date: 2025-11-18 16:49:52.491832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '414e1a985da3'
down_revision: Union[str, None] = 'd89252a2c25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('merchants', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('merchants', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('merchants', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('merchants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('punch_programs', sa.Column('expiration_enabled', sa.Boolean(), nullable=True))
    op.add_column('punch_programs', sa.Column('expiration_months', sa.Integer(), nullable=True))
    op.add_column('punch_programs', sa.Column('expiration_type', sa.Text(), nullable=True))
    op.add_column('punch_programs', sa.Column('expiration_extension_months', sa.Integer(), nullable=True))
    op.add_column('punch_programs', sa.Column('expiration_max_months', sa.Integer(), nullable=True))
    op.add_column('punch_programs', sa.Column('expiration_warning_days', sa.Integer(), nullable=True))
    op.add_column('punch_programs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('punch_programs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('wallet_cards', sa.Column('lifetime_punches', sa.Integer(), nullable=True))
    op.add_column('wallet_cards', sa.Column('lifetime_rewards', sa.Integer(), nullable=True))
    op.add_column('wallet_cards', sa.Column('visit_streak', sa.Integer(), nullable=True))
    op.add_column('wallet_cards', sa.Column('last_visit_date', sa.DateTime(), nullable=True))
    op.add_column('wallet_cards', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('wallet_cards', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.add_column('wallet_cards', sa.Column('expiration_notified', sa.Boolean(), nullable=True))
    op.add_column('wallet_cards', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('wallet_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('wallet_cards', 'updated_at')
    op.drop_column('wallet_cards', 'expiration_notified')
    op.drop_column('wallet_cards', 'last_activity_at')
    op.drop_column('wallet_cards', 'expires_at')
    op.drop_column('wallet_cards', 'last_visit_date')
    op.drop_column('wallet_cards', 'visit_streak')
    op.drop_column('wallet_cards', 'lifetime_rewards')
    op.drop_column('wallet_cards', 'lifetime_punches')
    op.alter_column('punch_programs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('punch_programs', 'updated_at')
    op.drop_column('punch_programs', 'expiration_warning_days')
    op.drop_column('punch_programs', 'expiration_max_months')
    op.drop_column('punch_programs', 'expiration_extension_months')
    op.drop_column('punch_programs', 'expiration_type')
    op.drop_column('punch_programs', 'expiration_months')
    op.drop_column('punch_programs', 'expiration_enabled')
    op.alter_column('merchants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('merchants', 'updated_at')
    op.drop_column('merchants', 'longitude')
    op.drop_column('merchants', 'latitude')
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('merchant_locations')
    # ### end Alembic commands ###
