"""add_wallet_customization_fields

Revision ID: 57c063ec0fe3
Revises: 040e8abf27ea
Create Date: 2025-10-24 18:32:07.389344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c063ec0fe3'
down_revision: Union[str, None] = '040e8abf27ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('wallet_strip_color', sa.Text(), nullable=True))
    op.drop_constraint('fk_profiles_auth_users', 'profiles', type_='foreignkey')
    op.add_column('punch_programs', sa.Column('wallet_filled_icon_url', sa.Text(), nullable=True))
    op.add_column('punch_programs', sa.Column('wallet_empty_icon_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('punch_programs', 'wallet_empty_icon_url')
    op.drop_column('punch_programs', 'wallet_filled_icon_url')
    op.create_foreign_key('fk_profiles_auth_users', 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_column('merchants', 'wallet_strip_color')
    # ### end Alembic commands ###
