"""add device registration and update info on passes

Revision ID: 6eb2ef780c49
Revises: 1fa6d9523795
Create Date: 2025-09-18 15:52:35.693760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb2ef780c49'
down_revision: Union[str, None] = '1fa6d9523795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_device_regs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('device_library_id', sa.Text(), nullable=False),
    sa.Column('push_token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['wallet_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.add_column('wallet_cards', sa.Column('auth_token', sa.Text(), nullable=True))
    op.add_column('wallet_cards', sa.Column('update_tag', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_cards', 'update_tag')
    op.drop_column('wallet_cards', 'auth_token')
    op.drop_table('wallet_device_regs')
    # ### end Alembic commands ###
