"""added google wallet custom

Revision ID: d89252a2c25d
Revises: 381781fb05f6
Create Date: 2025-10-27 15:54:11.865526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89252a2c25d'
down_revision: Union[str, None] = '381781fb05f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('punch_programs', sa.Column('google_program_details', sa.Text(), nullable=True))
    op.add_column('punch_programs', sa.Column('google_terms_conditions', sa.Text(), nullable=True))
    op.add_column('punch_programs', sa.Column('google_website_url', sa.Text(), nullable=True))
    op.add_column('punch_programs', sa.Column('google_help_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('punch_programs', 'google_help_url')
    op.drop_column('punch_programs', 'google_website_url')
    op.drop_column('punch_programs', 'google_terms_conditions')
    op.drop_column('punch_programs', 'google_program_details')
    # ### end Alembic commands ###
